### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tabrezm** [tabrezm/dotfiles#1]
- [x] forgit: https://github.com/wfxr/forgit
- [ ] ripgrep: https://github.com/BurntSushi/ripgrep, https://github.com/junegunn/fzf?tab=readme-ov-file#3-interactive-ripgrep-integration
- [ ] fzf: https://github.com/junegunn/fzf/wiki
